# Generated by Django 5.0.14 on 2026-05-30 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_admin', models.CharField(max_length=200)),
                ('telefono_admin', models.CharField(max_length=20)),
                ('correo_admin', models.EmailField(max_length=254, unique=True)),
                ('contrasena_admin', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('domicilio', models.TextField()),
                ('modelo_dron', models.CharField(max_length=100)),
                ('num_serie_dron', models.CharField(max_length=100)),
                ('fecha_act_dron', models.DateField()),
                ('num_serie_generador', models.CharField(max_length=100)),
                ('modelo_generador', models.CharField(max_length=100)),
                ('fecha_act_generador', models.DateField()),
                ('num_serie_control', models.CharField(max_length=100)),
                ('fecha_act_control', models.DateField()),
            ],
        ),
    ]
