# Generated by Django 5.0.14 on 2026-06-02 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='telefono_admin',
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('modelo_dron', models.CharField(max_length=100)),
                ('equipo', models.CharField(max_length=100)),
                ('tipo_servicio', models.CharField(max_length=50)),
                ('fecha_cita', models.DateField()),
                ('hora_cita', models.CharField(max_length=10)),
                ('descripcion', models.TextField()),
                ('estatus', models.CharField(default='Pendiente', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
        ),
    ]
