# Generated by Django 5.0.14 on 2026-07-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_usuario_foto_alter_cita_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='telefono_admin',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
