# Generated by Django 5.0.14 on 2026-07-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_administrador_telefono_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='foto_admin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='telefono_admin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
