# Generated by Django 5.0.14 on 2026-07-14 04:01

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_administrador_id_alter_cita_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_act_control',
            field=models.DateField(validators=[app.models.validar_fecha]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_act_dron',
            field=models.DateField(validators=[app.models.validar_fecha]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_act_generador',
            field=models.DateField(validators=[app.models.validar_fecha]),
        ),
    ]
